blank_issues_enabled: false
contact_links:
  - name: Question or help
    url: https://github.com/prisant-labs/obsidian-tag-visibility/discussions
    about: Ask a question or get help in Discussions.
